### ISSUE TITLE
Support for linux/arm is ignored

### ISSUE THREAD

**Issue by amsross** [Rantanen/node-jitterbuffer#10]
I'm trying to add support for linux/arm for use on a Raspberry Pi. Following the instructions in the README in every possible interpretation led me to the addition of 6 additional files (just in case):
```
        new file:   deps/config/celt-0.7.1/linux/arm/config.h
        new file:   deps/config/celt-0.7.1/linux/arm/include/speex/speex_config_types.h
        new file:   deps/config/celt-0.7.1/linux/arm/speex/speex_config_types.h
        new file:   deps/config/speex-1.2rc1/linux/arm/config.h
        new file:   deps/config/speex-1.2rc1/linux/arm/include/speex/speex_config_types.h
        new file:   deps/config/speex-1.2rc1/linux/arm/speex/speex_config_types.h
```

Even with these files added to `deps/config/[...]/linux/arm`, I'm still getting an `EBADPLATFORM` from `npm install ../my/local/jitterbuffer`:
```
36 error code EBADPLATFORM
37 error notsup Unsupported
37 error notsup Not compatible with your operating system or architecture: jitterbuffer@0.1.10
37 error notsup Valid OS:    linux,darwin,win32
37 error notsup Valid Arch:  x64
37 error notsup Actual OS:   linux
37 error notsup Actual Arch: arm
```

Am I misunderstanding some part of this?

**Comment by amsross** [comment]
I didn't understand npm's message and the fact that it is tied to the `package.json` setup.

Editing `cpu` property in `package.json` resolved this.

**Comment by Rantanen** [comment]
Added a note concerning this to the README.md. Hopefully that'll help whoever adds the next OS/architecture.

**Comment by amsross** [comment]
Part of the trouble leading to this issue is the fact that the README says the following:

----
Add new supported platforms by running `./configure` in `deps/speex-1.2rc1` and copying the following files:

* `config.h`
* `include/speex/speex_config_types.h`

to `deps/config/celt-0.7.1/<os>/<arch>` maintaining the relative path. See the existing platforms for an example.

----

It looks to me from the existing platforms that `include/speex/speex_config_types.h` should be placed in `deps/config/speex-1.2rc1/speex/speex_config_types.h`, and not in `deps/config/celt-0.7.1/include/speex/speex_config_types.h`. In this case both the config directory and the relative path seem to be incorrect in the instructions.

**Comment by Rantanen** [comment]
Oh. Oops.

I'll fix this tomorrow.
