### ISSUE TITLE
Printing "Destroyer" when garbage collected

### ISSUE THREAD

**Issue by Prior99** [Rantanen/node-jitterbuffer#14]
When Garbage collection for a jitterbuffer is triggered, it will log `Destroyer`.

I think this line needs to be removed: https://github.com/Rantanen/node-jitterbuffer/blob/cefae8e0ea68d764920b11ed23c953152a33c50b/src/node-jitterbuffer.cc#L27

**Comment by Rantanen** [comment]
Fixed in 0.1.14, thanks for pointing that out!
