### ISSUE TITLE
Warning about negative buffering

### ISSUE THREAD

**Issue by justinmchase** [Rantanen/node-jitterbuffer#8]
```
warning: jitter buffer sees negative buffering, your code might be broken. Value is  -6
```

This is happening while just playing the mp3 example in `node-electron` any clues?

**Comment by Prior99** [comment]
I somtimes experience this issue when producing heavy load in the mainloop, like for example iterating over the whole buffer or similiar stuff.

**Comment by Rantanen** [comment]
Hm. Node-mumble might have problem with the timer implementation. I believe this is caused by requesting more frames from the jitterbuffer than has been buffered.
